### ISSUE TITLE
Ungenauigkeiten in eurem KanBan-Board

### ISSUE THREAD

**Issue by PhillipSteph** [Erfurter-Bahner/Cosmos-Service#4]
Schönen guten Tag, liebes Team hinter dem AmigOS.

Ich bin wirklich erstaunt über den Fortschritt eures Projekts, jedoch noch mehr über die Art und Weise, wie ihr euer agiles KanBan-Board nutzt. Die Tickets in eurer ToDo-Spalte sind so unglaublich vage formuliert und völlig ohne jegliche Beschreibung. Für jemanden, der nicht tief in euer Projekt involviert ist, sind diese schlichtweg unbrauchbar. Habt ihr jemals auch nur eine Minute in einem Kurs zu Systemanalyse oder Systementwicklung verbracht? Bei dieser Art der Umsetzung verspüre ich ein starkes Fremdschämen.

Trotzdem wünsche ich euch eine herausragende Woche und natürlich weiterhin viel Spaß bei der Entwicklung!

Beste Grüße,  
Phillip Stephan  
CEO of FlipFlOS inc.  
www.ichluegenichtuebermeineadresse.com

**Comment by vinzenzgeisler** [comment]
Danke für Ihre Hinweise. 
Unser Team ist stets bemüht jenes Produkt weiterzuentwickeln und höchste Kundenzufriedenheit zu erreichen. Für weitere Frage stehe ich Ihnen gerne über den direkten Austausch zur Verfügung. Noch eine schöne Woche.

Vinzenz Geisler
PO Gruppe 1
